### ISSUE TITLE
"Cannot get class MTerrainMaterial" error when exporting 

### ISSUE THREAD

**Issue by nickpolet** [mohsenph69/Godot-MTerrain-plugin#18]
Building the latest version of master, then trying to export a project results in the following error:

![image](https://github.com/mohsenph69/Godot-MTerrain-plugin/assets/5023909/d789814b-5c11-456d-8762-6a62d2cc882c)

Reverting back to an older version before the MTerrainMaterial addition seems to work well. I've tried clearing the .godot just in case there was something cached incorrectly in there, but no difference. I've also tried release & debug builds, but to no avail.

Any ideas what might be happening here?

**Comment by mohsenph69** [comment]
That is really strange, Recently I created a demo and I exported for windows and linux, in both cases it worked fine!
Download executable file for linux:
https://drive.google.com/file/d/1909n57cXXfnO2HNdj45zKmFsxWzkMHtk/view?usp=sharing

Download executable file for windows:
https://drive.google.com/file/d/1WJBxvBy7R8UVTe0kZo3FGi6Nghv1_LQn/view?usp=sharing

The demo above also use MTerrainMaterial

Recently I added a new release "v0.9.2", try to use that if you are using the older version and see if that works

if that does not work, send me a minimal project file so I can reproduce the bug, and see what is the problem, Because as this error does not happen to me I have no idea how to solve it!

**Comment by nickpolet** [comment]
Okay, used 0.9.2 instead of 0.9.1 and everything works great. Thanks for the tip.

I didn't see that there had been a new release. All good now though.

Absolutly loving this add on BTW. 16km by 16km running so performantely is amazing in Godot. Such a powerful add on.

Will close this issue out now.
